---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: democrds.example.com
spec:
  group: example.com
  names:
    kind: DemoCrd
    listKind: DemoCrdList
    plural: democrds
    singular: democrd
    shortNames:
    - dc
  scope: Namespaced # Namespaced / Cluster
  versions:
  - name: v1
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: DemoCrd is the Schema for the democrds API
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
            type: string
          kind:
            description: Kind is a string value representing the REST resource this object represents
            type: string
          metadata:
            type: object 
          spec:
            description: Spec defines the desired state of DemoCrd
            x-kubernetes-preserve-unknown-fields: true
            type: object
            properties:
              description:
                type: string
              info:
                type: array
                items:
                  type: string
              count:
                type: integer
              extraInfo:
                type: object
                properties:
                  infoOne:
                    type: string
                  infoTwo:
                    type: string
          status:
            description: Status defines the observed state of DemoCrd
            x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
---